Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using ControleClientesMvc.Models;
using System.Collections.Generic;
using ControleClientesMvc.ApiClients;
using ControleClientesMvc.Services;

public class ClientesController : Controller
{
    private readonly ObterRelatorioClientesApiClient _obterRelatorioClientesApi;
    private readonly ExcluirClienteApiClient _excluirClienteApiClient;
    private readonly ClienteCadastrarApiClient _clienteCadastrarApiClient;
    private readonly ObterDadosClienteApiClient _obterDadosClienteApiClient;
    private readonly AtualizarDadosClienteApiClient _atualizarDadosClienteApiClient;

    public ClientesController(AutenticacaoService _autenticacaoService)
    {
        _obterRelatorioClientesApi = new ObterRelatorioClientesApiClient(_autenticacaoService);
        _excluirClienteApiClient = new ExcluirClienteApiClient(_autenticacaoService);
        _clienteCadastrarApiClient = new ClienteCadastrarApiClient(_autenticacaoService);
        _obterDadosClienteApiClient = new ObterDadosClienteApiClient(_autenticacaoService);
        _atualizarDadosClienteApiClient = new AtualizarDadosClienteApiClient(_autenticacaoService);
    }
    private async Task<int> ObterIdUsuario()
    {
        var idString = HttpContext?.Request.Cookies["UserId"];

        if (!string.IsNullOrEmpty(idString))
        {
            if (int.TryParse(idString, out int userId))
            {
                return userId;
            }
        }

        await Task.CompletedTask;

        return 0;
    }
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        if (await ObterIdUsuario() != 0)
        {
            var relatorioClientes = await _obterRelatorioClientesApi.ObterRelatorioClientesAsync(await ObterIdUsuario());

            if (relatorioClientes == null || !relatorioClientes.Any())
            {
                TempData["AvisoBoasVindas"] = "Olá, você ainda não possui nenhum cliente cadastrado. Que tal começar agora?";
            }
            return View("Index", relatorioClientes);
        }

        return RedirectToAction("Login", "Usuarios");
    }

    [HttpGet]
    public IActionResult Criar()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Criar(ClienteModel cliente)
    {

        if (!ModelState.IsValid)
        {
            return View("Criar", cliente);
        }

        cliente.Id = await ObterIdUsuario();

        string mensagem = await _clienteCadastrarApiClient.CadastrarClienteAsync(cliente);

        if (mensagem.Contains("sucesso"))
        {
            TempData["SucessoCriarCliente"] = mensagem;

            var novoCliente = new ClienteModel();
            return View("Criar", novoCliente);
        }
        else
        {
            TempData["ErroCriarCliente"] = mensagem;
            return View("Criar", cliente);
        }
    }

    [HttpGet]
    public async Task<IActionResult> Editar(int id)
    {
        if (id <= 0)
        {
            return BadRequest(new { Message = "ID do cliente inválido." });
        }

        var cliente = await _obterDadosClienteApiClient.ObterDadosClienteAsync(id);

        if (cliente != null)
        {
            return View("Editar", cliente);
        }
        else
        {
            return RedirectToAction("Index", "Clientes");
        }
    }

    [HttpPost]
    public async Task<IActionResult> Editar(ClienteModel cliente)
    {
        if (!ModelState.IsValid)
        {
            return View("Editar", cliente);
        }

        var mensagem = await _atualizarDadosClienteApiClient.AtualizarDadosClienteAsync(cliente);

        if (mensagem.Contains("sucesso"))
        {
            TempData["SucessoEditarCliente"] = mensagem;

            return View("Editar", cliente);
        }
        else
        {
            TempData["ErroEditarCliente"] = mensagem;

            return View("Editar", cliente);
        }
    }
    [HttpPost]
    public async Task<IActionResult> Excluir(int id)
    {
        if (id > 0)
        {
            var status = await _excluirClienteApiClient.ExcluirClienteAsync(id);

            if (status == "Cliente excluído com sucesso!")
            {
                TempData["SuccessExcluirCliente"] = "Cliente excluído com sucesso!";
            }
            else
            {
                TempData["ErrorExcluirCliente"] = status;
            }
        }
        else
        {
            TempData["ErrorExcluirCliente"] = "O ID do cliente deve ser maior que zero.";
        }

        return RedirectToAction("Index");
    }
}

Controllers/CobrancasController.cs
using Microsoft.AspNetCore.Mvc;
using ControleClientesMvc.Models;
using ControleClientesMvc.ApiClients;
using ControleClientesMvc.Services;

public class CobrancasController : Controller
{
    private readonly CadastrarCobrancaApiClient _cadastrarCobrancasApiClient;
    private readonly ObterRelatorioDividasApiClient _obterRelatorioDividasApiClient;
    private readonly ExcluirCobrancaApiClient _excluirCobrancaApiClient;
    private readonly ObterDetalhesCobrancaApiClient _obterDetalhesCobrancaApiClient;
    private readonly AtualizarCobrancaApiClient _atualizarCobrancaApiClient;

    public CobrancasController(AutenticacaoService _autenticacaoService)
    {
        _cadastrarCobrancasApiClient = new CadastrarCobrancaApiClient(_autenticacaoService);
        _obterRelatorioDividasApiClient = new ObterRelatorioDividasApiClient(_autenticacaoService);
        _excluirCobrancaApiClient = new ExcluirCobrancaApiClient(_autenticacaoService);
        _obterDetalhesCobrancaApiClient = new ObterDetalhesCobrancaApiClient(_autenticacaoService);
        _atualizarCobrancaApiClient = new AtualizarCobrancaApiClient(_autenticacaoService);
    }

    [HttpGet]
    public async Task<IActionResult> Index(int id, string nome)
    {
        if (id <= 0)
        {
            return RedirectToAction("Index", "Clientes");
        }

        ViewData["NomeCliente"] = nome;

        TempData["ClienteId"] = id;

        var cobrancas = await _obterRelatorioDividasApiClient.ObterRelatorioDividasAsync(id);

        if (cobrancas == null || !cobrancas.Any())
        {
            TempData["AvisoMessage"] = "Nenhuma cobrança encontrada para o cliente.";
        }

        return View("Index", cobrancas);
    }
    [HttpGet]
    public IActionResult Criar()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Criar(CobrancaModel cobranca)
    {

        if (cobranca.Descricao == null || cobranca.Valor == 0 || cobranca.Data == DateTime.MinValue || cobranca._Status == 0)
        {
            return View(cobranca);
        }

        int tempID = Convert.ToInt32(TempData["ClienteId"]);
        cobranca.Id = tempID;

        switch (cobranca._Status)
        {
            case 1:
                cobranca.Status = true;
                break;
            case 2:
                cobranca.Status = false;
                break;
            default:
                break;
        }

        var mensagem = await _cadastrarCobrancasApiClient.CadastrarCobrancasAsync(cobranca);

        if (mensagem.Contains("sucesso"))
        {
            ViewData["SucessoMessage"] = mensagem;
            return View("Criar", cobranca);
        }
        else
        {
            ViewData["ErroMessage"] = mensagem;
            return View("Criar", cobranca);
        }
    }
    [HttpGet]
    public async Task<IActionResult> Editar(int id)
    {
        if (id <= 0)
        {
            return BadRequest(new { Message = "ID da cobrança inválido." });
        }

        TempData["CobrancaId"] = id;

        var cobranca = await _obterDetalhesCobrancaApiClient.ObterDetalhesCobrancaAsync(id);

        if (cobranca != null)
        {
            var model = new CobrancaModel
            {
                Descricao = cobranca.Descricao,
                Valor = cobranca.Valor,
                _Data = cobranca.Data.ToString("yyyy-MM-dd"),
                _Status = cobranca.Status ? 1 : 2
            };

            return View("Editar",model);
        }
        else
        {
            return NotFound(new { Message = "Cobrança não encontrada." });
        }
    }

    [HttpPost]
    public async Task<IActionResult> Editar(CobrancaModel cobranca)
    {
        int tempID = Convert.ToInt32(TempData["CobrancaId"]);
        cobranca.Id = tempID;

        switch (cobranca._Status)
        {
            case 1:
                cobranca.Status = true;
                break;
            case 2:
                cobranca.Status = false;
                break;
            default:
                break;
        }

        var mensagem = await _atualizarCobrancaApiClient.AtualizarCobrancaAsync(cobranca);

        if (mensagem.Contains("sucesso"))
        {
            ViewData["SucessoMessage"] = mensagem;
            return View("Editar", cobranca);
        }
        else
        {
            ViewData["ErroMessage"] = mensagem;
            return View("Editar", cobranca);
        }

    }
    [HttpPost]
    public async Task<IActionResult> Excluir(int id)
    {
        if (id > 0)
        {
            var mensagem = await _excluirCobrancaApiClient.ExcluirCobrancaAsync(id);

            if (mensagem.Contains("sucesso"))
            {
                TempData["SucessoMessage"] = mensagem;
                return Json(new { success = true });
            }
            else
            {
                TempData["ErroMessage"] = mensagem;
                return Json(new { success = false });
            }
        }
        else
        {
            TempData["ErroMessage"] = "O ID do cliente deve ser maior que zero.";
            return Json(new { success = false });
        }
    }

}

Views/Clientes/Criar.cshtml
@model ControleClientesMvc.Models.ClienteModel

<div class="header-container">
    <h2 class="fw-bold">Cadastrar novo cliente</h2>
    <a href="@Url.Action("Index", "Clientes")" class="btn-cancelar">Cancelar</a>
</div>
<div class="table-container">
    @if (TempData["SucessoCriarCliente"] != null)
    {
        <div class="alert alert-success">
            @TempData["SucessoCriarCliente"]
        </div>
    }
    @if (TempData["ErroCriarCliente"] != null)
    {
        <div class="alert alert-success">
            @TempData["ErroCriarCliente"]
        </div>
    }
    <form asp-action="Criar" method="post" class="row g-3">
        <div class="col-md-6">
            <label asp-for="Nome" class="form-label">Nome</label>
            <input asp-for="Nome" class="form-control" placeholder="Nome do Cliente" required />
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div class="col-md-6">
            <label asp-for="Documento" class="form-label">Documento</label>
            <input asp-for="Documento" class="form-control" placeholder="Número do Documento" required />
            <span asp-validation-for="Documento" class="text-danger"></span>
        </div>
        <div class="col-md-6">
            <label asp-for="Telefone" class="form-label">Telefone</label>
            <input asp-for="Telefone" class="form-control" placeholder="Telefone do Cliente" required />
            <span asp-validation-for="Telefone" class="text-danger"></span>
        </div>
        <div class="col-md-6">
            <label asp-for="Endereco" class="form-label">Endereço</label>
            <input asp-for="Endereco" class="form-control" placeholder="Endereço do Cliente" required />
            <span asp-validation-for="Endereco" class="text-danger"></span>
        </div>
        <div class="btn-cadastrar-container col-12">
            <button type="submit" class="btn-cadastrar">Cadastrar</button>
        </div>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}


<style>
    .header-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
    }

    .table-container {
        width: 100%;
        margin: 0;
        -webkit-overflow-scrolling: touch;
    }

    .btn-cancelar {
        background-color: red;
        color: white;
        border: none;
        border-radius: 4px;
        padding: 10px 20px;
        cursor: pointer;
        font-size: 14px;
        text-decoration: none;
    }

    .btn-cadastrar-container {
        display: flex;
        justify-content: flex-end;
        margin-top: 20px;
    }

    .btn-cadastrar {
        background-color: Black;
        color: white;
        border: none;
        border-radius: 4px;
        padding: 10px 20px;
        cursor: pointer;
        font-size: 14px;
    }

    .form-label {
        font-weight: bold;
    }
</style>

Views/Clientes/Editar.cshtml
@model ControleClientesMvc.Models.ClienteModel

<div class="header-container">
    <h2 class="fw-bold">Atualizar dados do cliente</h2>
    <a href="@Url.Action("Index", "Clientes")" class="btn-cancelar">Cancelar</a>
</div>
<div class="table-container">
    @if (TempData["SucessoEditarCliente"] != null)
    {
        <div class="alert alert-success">
            @TempData["SucessoEditarCliente"]
        </div>
    }
    @if (TempData["ErroEditarCliente"] != null)
    {
        <div class="alert alert-success">
            @TempData["ErroEditarCliente"]
        </div>
    }
    <form asp-action="Editar" method="post" class="row g-3">
        <div class="col-md-6">
            <label for="inputName" class="form-label">Nome</label>
            <input type="text" class="form-control" id="inputName" name="Nome" value="@Model.Nome" placeholder="Nome do Cliente" required />
        </div>
        <div class="col-md-6">
            <label for="inputDocument" class="form-label">Documento</label>
            <input type="text" class="form-control" id="inputDocument" name="Documento" value="@Model.Documento" placeholder="Número do Documento" required />
        </div>
        <div class="col-md-6">
            <label for="inputPhone" class="form-label">Telefone</label>
            <input type="tel" class="form-control" id="inputPhone" name="Telefone" value="@Model.Telefone" placeholder="Telefone do Cliente" required />
        </div>
        <div class="col-md-6">
            <label for="inputAddress" class="form-label">Endereço</label>
            <input type="text" class="form-control" id="inputAddress" name="Endereco" value="@Model.Endereco" placeholder="Endereço do Cliente" required />
        </div>
        <div class="btn-cadastrar-container col-12">
            <button type="submit" class="btn-cadastrar">Atualizar</button>
        </div>
    </form>
</div>

<style>
    .header-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
    }

    .table-container {
        width: 100%;
        margin: 0;
        -webkit-overflow-scrolling: touch;
    }

    .btn-cancelar {
        background-color: red;
        color: white;
        border: none;
        border-radius: 4px;
        padding: 10px 20px;
        cursor: pointer;
        font-size: 14px;
        text-decoration: none;
    }

    .btn-cadastrar-container {
        display: flex;
        justify-content: flex-end;
        margin-top: 20px;
    }

    .btn-cadastrar {
        background-color: Black;
        color: white;
        border: none;
        border-radius: 4px;
        padding: 10px 20px;
        cursor: pointer;
        font-size: 14px;
    }

    .form-label {
        font-weight: bold;
    }
</style>

Views/Clientes/Index.cshtml
@model List<ControleClientesMvc.Models.CobrancaModel>

<div class="header-container">
    <h2 class="fw-bold">Clientes</h2>
    <a href="@Url.Action("Criar", "Clientes")" class="btn-cadastrar">Cadastrar</a>
</div>
<div class="table-container">
    @if (TempData["AvisoBoasVindas"] != null)
    {
        <div class="alert alert-primary">
            @TempData["AvisoBoasVindas"]
        </div>
    }
    @if (TempData["SuccessExcluirCliente"] != null)
    {
        <div class="alert alert-success">
            @TempData["SuccessExcluirCliente"]
        </div>
    }
    @if (TempData["ErrorExcluirCliente"] != null)
    {
        <div class="alert alert-danger">
            @TempData["ErrorExcluirCliente"]
        </div>
    }
    <table>
        <thead>
            <tr>
                <th style="width:5%">ID</th>
                <th style="width:35%">Nome</th>
                <th style="width:10%">Pagos</th>
                <th style="width:10%">Abertos</th>
                <th style="width:10%">Atrasados</th>
                <th style="width:30%"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cliente in Model)
            {
                <tr>
                    <td class="text-black">@cliente.Id</td>
                    <td class="text-black">@cliente.Nome</td>
                    <td><div class="circleGreen">@cliente.Pagos</div></td>
                    <td><div class="circleBlue">@cliente.Abertos</div></td>
                    <td><div class="circleRed">@cliente.Atrasados</div></td>
                    <td>
                        <div class="action-buttons">
                            <a href="@Url.Action("Editar", "Clientes", new { id = cliente.Id, nome = cliente.Nome })" class="edit-button">
                                <i class="fas fa-edit"></i>
                            </a>
                            <form asp-action="Excluir" asp-controller="Clientes" method="post" style="display:inline;">
                                <input type="hidden" name="id" value="@cliente.Id" />
                                <button type="submit" class="delete-button" onclick="return confirm('Tem certeza de que deseja excluir este cliente?');">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </form>
                            <a href="@Url.Action("Index", "Cobrancas", new { id = cliente.Id, nome = cliente.Nome })" class="charges-button" style="text-decoration:none">Cobranças</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<style>
    .table-container {
        overflow-x: auto;
        width: 100%;
        margin-bottom: 50px;
        -webkit-overflow-scrolling: touch;
    }

    table {
        border-collapse: collapse;
        width: 100%;
        border: 1px solid #ddd;
        table-layout: auto;
    }

    th, td {
        text-align: center;
        padding: 19px;
        vertical-align: middle;
    }

    th {
        background-color: black;
        color: white;
    }

        th:first-child, td:first-child {
            text-align: left;
        }

    tr:nth-child(even) {
        background-color: #f1f1f1;
    }

    tr:nth-child(odd) {
        background-color: white;
    }

    .text-black {
        color: black;
    }

    .circleGreen, .circleBlue, .circleRed {
        width: 25px; 
        height: 25px; 
        border-radius: 50%;
        display: flex;
        justify-content: center;
        align-items: center;
        color: black;
        font-size: 15px; 
        font-weight: bold;
        line-height: 25px; 
        text-align: center;
        margin: 0 auto;
    }

    .circleGreen {
        background-color: #6ef173;
    }

    .circleBlue {
        background-color: #6db4ff;
    }

    .circleRed {
        background-color: #ff9292;
    }

    .edit-button, .delete-button {
        display: inline-flex; 
        align-items: center; 
        justify-content: center; 
        width: 25px; 
        height: 25px; 
        cursor: pointer;
        border-radius: 4px;
        color: white;
        font-size: 17px; 
    }

    .edit-button {
        background-color: blue;
    }

    .delete-button {
        background-color: red;
    }

    .charges-button {
        background-color: black;
        color: white;
        border: none;
        border-radius: 4px;
        padding: 0 15px; 
        height: 25px; 
        line-height: 25px; 
        cursor: pointer;
        font-size: 14px; 
        vertical-align: middle;
        display: inline-flex;
        align-items: center; 
        justify-content: center; 
    }

    .action-buttons {
        display: flex;
        align-items: center; 
        justify-content: flex-end; 
        gap: 10px; 
    }

    .header-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
    }

    .btn-cadastrar {
        background-color: black;
        color: white;
        border: none;
        border-radius: 4px;
        padding: 10px 20px;
        cursor: pointer;
        font-size: 14px;
        text-decoration: none;
    }
</style>